### ISSUE TITLE
glove.6B.100d.txtglove.6B

### ISSUE THREAD

**Issue by HodaFakharzade** [ajinkyaT/CNN_Intent_Classification#2]
Hi 
thanks for sharing your code! 
would u mind to upload "glove.6B.100d.txt" file pls?
I would like to check this code my self but I got stuck with this line:
`f = open(os.path.join(GLOVE_DIR, 'glove.6B.100d.txt'), encoding='utf-8')`
thank u!

**Comment by ajinkyaT** [comment]
Hi 

Thank you for your interest. You can download them from [http://nlp.stanford.edu/data/glove.6B.zip](http://nlp.stanford.edu/data/glove.6B.zip) and extract it under the directory, BASE_DIR + '/glove.6B/'.
i cannot upload it because file size is too large.
